# Normal Options
arrowParens: "always"
bracketSpacing: true
embeddedLanguageFormatting: "auto"
endOfLine: "lf"
htmlWhitespaceSensitivity: "strict"
bracketSameLine: false
jsxSingleQuote: false
printWidth: 120
quoteProps: "as-needed"
semi: true
singleQuote: false
tabWidth: 4
trailingComma: "none"
useTabs: false

overrides:
    - files:
          - "*.html"
          - "*.yml"
          - "*.yaml"
          - "*.json"
          - "*.css"
          - "*.scss"
      options:
          tabWidth: 4
